 default: &default
   dispatchers:
     - polling_interval: 1
       batch_size: 500
       recurring_tasks:
         slip_creation_job:
           class: SlipCreationJob
           schedule: every day at 10 am

   workers:
     - queues: "*"
       threads: 5
       processes: 1
       polling_interval: 0.1

 development:
  <<: *default

 test:
  <<: *default

 production:
  <<: *default
